server:
  port: 8090

spring:
  datasource:
    username: root
    #公司虚拟机
    url: jdbc:mysql://192.168.72.132:33306/test?useUnicode=true&characterEncoding=UTF8&serverTimezone=Hongkong
    password: 123456

    #公司本地主机
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF8&serverTimezone=Hongkong
#    password: root

    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    db-config:
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_null

# MinIo文件服务器
minio:
  endpoint: http://192.168.72.132:9000
  accessKey: minioadmin
  secretKey: minioadmin
  communityBucket: community
  wikiBucket: wiki
  sysBucket: sys
  # 内网minio
  localAddr: http://192.168.72.132:9000
  # 外网minio
  remoteAddr: http://192.168.72.132:9000
  # 实际存储数据库,使用占位符代替
  realAddr: '@-@MINIO@-@'
  # 是否据王判断正则
  patternAddr: http://[0-9]*.[0-9]*.[0-9]*.[0-9]*:9000
  # 判断是否为本地
  localIpPrefix: 192.168



# 配置日志
logging:
  config: classpath:log4j2-dev.xml

