server:
  port: 8090

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    #公司虚拟机
    url: jdbc:mysql://192.168.72.138:33306/test?useUnicode=true&characterEncoding=UTF8&serverTimezone=Hongkong
    password: 123456
    hikari:
      ## 最小空闲连接数量
      minimum-idle: 5
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 10
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000



    #公司本地主机
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF8&serverTimezone=Hongkong
#    password: root



mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    db-config:
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_null

# MinIo文件服务器
minio:
  endpoint: http://192.168.72.138:9000
  accessKey: minioadmin
  secretKey: minioadmin
  communityBucket: community
  uploadBucket: upload
  sysBucket: sys
  # 内网minio
  localAddr: http://192.168.72.138:9000
  # 外网minio
  remoteAddr: http://192.168.72.138:9000
  # 实际存储数据库,使用占位符代替
  realAddr: '@-@MINIO@-@'
  # 是否据王判断正则
  patternAddr: http://[0-9]*.[0-9]*.[0-9]*.[0-9]*:9000
  # 判断是否为本地
  localIpPrefix: 192.168



# 配置日志
logging:
  config: classpath:log4j2-dev.xml

