server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://192.168.142.128:33306/test?useUnicode=true&characterEncoding=UTF8&serverTimezone=Hongkong
    password: 123456
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF8&serverTimezone=Hongkong
    username: root
#    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml


