server:
  port: 8080

#公司本地主机
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF8&serverTimezone=Hongkong
#    password: root


spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    #公司虚拟机
    url: jdbc:mysql://mysql:3306/aspn?useUnicode=true&characterEncoding=UTF8&serverTimezone=Hongkong
    username: root
    password: aspn2021
    hikari:
      ## 最小空闲连接数量
      minimum-idle: 10
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 20
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
  mail:
    host: mail.aspnc.com
    port: 25
    password: aspn20070312
    username: aspn300@aspnc.com
    properties.mail.smtp:
      #      socketFactoryCalss: javax.net.ssl.SSLSocketFactory
      timeout: 5000
      connectiontimeout: 5000
      writetimeout: 5000
    default-encoding: UTF-8


mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    db-config:
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_null

# MinIo文件服务器
minio:
  endpoint: http://minio:9000
  accessKey: aspn
  secretKey: aspn2021
  communityBucket: community
  uploadBucket: upload
  sysBucket: sys
  # 内网minio
  localAddr: http://aspnc.com.cn:9000
  # 外网minio
  remoteAddr: http://aspnc.com.cn:9000
  # 实际存储数据库,使用占位符代替
  realAddr: '@-@MINIO@-@'
  # 是否据王判断正则
  patternAddr: 'http://aspnc.com.cn:9000'
  # 判断是否为本地
  localIpPrefix: http://aspnc.com.cn



# 配置日志
logging:
  config: classpath:log4j2-prod.xml


